#버전
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: lgcns
    

spec: 
  # 자원 공간의 낭비를 방지 및 관리의 편의성을 제공해주는 옵션
  revisionHistoryLimit: 2

  replicas: 2
  selector:
    matchLabels:
      app: order-pod

  template:
    metadata:
      labels:
        app: order-pod

    spec:
    #docker container
      containers:
      - name: order-container
        # ERC 경로
        image: 933090817123.dkr.ecr.us-east-2.amazonaws.com/order-daniel-backend:latest
        ports:
          - containerPort: 8888

        # autoscaler(pod) 작업을 위해서 추가함
        resources:
          # 컨테이너가 사용할수 있는 리소스의 최대치
          limits:
            cpu: "1"
            memory: "500Mi"
          # 컨테이너가 시작될떄 보장받아야 하는 최소 자원
          requests:
            cpu: "0.5"
            memory: "250Mi"


        # k8s - secret에 설정한 정보를 외부변수로 전환하는  작업
        # yaml에 있는 이름
        env: 
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_HOST

          - name: DB_ADMIN
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_ADMIN

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_PASSWORD 




---  #구분 지어야 함

#core service setting
apiVersion: v1

kind: Service

metadata:
  name: order-service
  namespace: lgcns

spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888        # container port를 의미*
  selector:
    app: order-pod      #selector의 name